#! /bin/sh

### BEGIN INIT INFO
# Provides:		power
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Power manager
### END INIT INFO


umask 022

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/home/garden/bin"

case "$1" in
  start)
	log_daemon_msg "Starting power manager" "power" || true
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/power.pid --name power --exec /home/garden/bin/keep_running -- -p/var/run/power.pid /home/garden/bin/power ; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping power manager" "power" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/power.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p /var/run/power.pid /home/garden/bin/power power && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/power {start|stop|status}" || true
	exit 1
esac

exit 0
